name: kobe
favicon: null
layout_spectrum: 0.5456533336546272
typography_spectrum: 0.5867119198665023
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9292645023670048
  lightness: 0.5362029536627233
  saturation: 0.12927540647797287
  rhythmicContrast: 0.34519642987288535
purpose: []
